### PR TITLE
Add common non-null constraint annotations

### LINKED ISSUE #203: Support for @NotEmpty and @NotBlank validation constraint
If I annotate a parameter with `javax.validation.constraints.NotNull`, it's automatically made mandatory in the GraphQL schema; the same should happen also for:

- `javax.validation.constraints.NotEmpty`
- `javax.validation.constraints.NotBlank`

but with these annotations, the parameter is still optional in the schema.

### PR DESCRIPTION
**Pull request by heruan**
Fixes #203

### CODE REVIEW

**Comment by kaqqao** [comment]
`@NotEmpty` seems tricky... it requires a non-empty collection, which means it should map to e.g. `[String!]!` not only `[String]!`. I have to think about how to achieve that nicely...

**Comment by heruan** [comment]
Hm, not sure I understand. Shouldn't this be as simple as

`@NotEmpty String -> String!`
`@NotEmpty List<String> -> [String]!`
`@NotEmpty List<@NotEmpty String>` -> [String!]!`

?

**Comment by kaqqao** [comment]
`[String]!` means _non-null list_ so an empty list would be OK, which violates `@NotEmpty` 😕
That's why I think `@NotEmpty List<String> -> [String!]!` i.e. _a non-null list that can not be empty_.

As for `@NotEmpty List<@NotEmpty String>` I guess it would be the same `[String!]!` as there's no way to express non-emptiness of strings directly (custom scalars would be a way out).

**Comment by kaqqao** [comment]
No clue why I was convinced `[!]!` is a non-empty list 🤨You're, of course, right.

**Pull request merged**
