### PR TITLE
Public ComplexityAnalyzer

### PR DESCRIPTION
**Pull request by antimony**
I want to write my own `ComplexityAnalysisInstrumentation` with micrometer integrated to track complexity distribution for example. 
Now I had to copy-paste whole complexity package because I can't construct `ComplexityAnalyzer` in my `ComplexityAnalysisInstrumentation` implementation. What do you think about making `ComplexityAnalyzer` public?

### CODE REVIEW

**Comment by kaqqao** [comment]
The tricky bit is that the current complexity analyzer is a nightmarish salad of private graphql-java API calls... Making the class itself public is ok, but it is likely that I'll have to rewrite the whole thing very very soon.
Could you instead get away with providing a custom ComplexityFunction? What exactly do you want to achieve?

**Comment by antimony** [comment]
I want to track result of ComplexityAnalyzer.collectFields via micrometer,  to add some alerts if complexity limit was exceeded and to build complexity distribution. Looks like here is the right place to do that: https://github.com/leangen/graphql-spqr/blob/46342dd3fc7b14b35f3fc52df66ed4bcfa95624c/src/main/java/io/leangen/graphql/execution/complexity/ComplexityAnalysisInstrumentation.java#L31
But I can't write my own ComplexityAnalysisInstrumentation and reuse ComplexityAnalyzer.

Custom ComplexityFunction allows me to track each node, but I want to track root node only (and also I need execution context to add some context information to micrometer)

**Comment by antimony** [comment]
Also I found an NPE on `__typename` field in request, please check it. 
If it's reasonable – I could rework this PR and revert public modifier change, leaving only NPE fix

**Comment by kaqqao** [comment]
Hey! Sorry for the silence. I wasn't able to work on this project for... a while. I made a huge update in order to switch to graphql-java v19.
Would you please be able to open a new PR, as this is now in a huge conflict with the upgrade.
I'm ok with making the class public, btw. One thing I'm unsure about though... Should selecting `__typename` really be free, complexity-wise? I think it should still increment the complexity score by 1, like any any other field by default. Do you agree?

**Comment by kaqqao** [comment]
The [new `ComplexityAnalyzer`](https://github.com/leangen/graphql-spqr/issues/450) is public.

**Pull request closed without merging**
