### PR TITLE
bump_graphql_17_4

### PR DESCRIPTION
**Pull request by indentia**

### CODE REVIEW

**Comment by indentia** [comment]
@kaqqao can this work?

**Comment by hzariv** [comment]
Is anyone reviewing this PR? This is aim to fix a security vulnerability in current release of SPQR.

**Comment by kaqqao** [comment]
I'm grateful to everyone involved, but I've opted to upgrade straight to graphql-java v19. See #433. I'll close this PR in light of that. New release coming soon.
If anyone cares to test the current master against their project before the release, I'd be grateful.

**Comment by indentia** [comment]
@kaqqao great are you doing graphql-spqr-spring-boot-starter as well

**Pull request closed without merging**
